spring:
  profiles: jms-template, jms-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61616
    user: taco
    password: test
    embedded:
      enabled: false

---
spring:
  profiles: rabbitmq-template, rabbitmq-listener
  rabbitmq:
    template:
      receive-timeout: 2
    host: localhost
    port: 5672
    username: taco
    password: test
    embedded:
      enabled: false